name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/little-big-h/buildenvironment/image:latest
      credentials:
         username: little-big-h
         password: 71589973e27e38bae496e2f4b49be18d2c4fc9f0
    steps:
    - uses: actions/checkout@v2
    - name: check
      run: |
        find . -name '*.cpp' -or -name '*.hpp' -exec clang-format -i -style=file '{}' ';'
        git status -s
        exit $(git status -s | wc -l)

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Release, Debug, Sanitize]
    container:
      image: docker.pkg.github.com/little-big-h/buildenvironment/wolframbased:latest
      credentials:
         username: little-big-h
         password: 71589973e27e38bae496e2f4b49be18d2c4fc9f0
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: configure
      run: |
        mkdir ${{ matrix.build-type }}
        cd ${{ matrix.build-type }}
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_CXX_FLAGS:STRING="-std=c++17" -DCMAKE_CXX_COMPILER:STRING=clang++-11 -DCMAKE_CXX_CLANG_TIDY=clang-tidy-11 ..
        cd ..
    - name: build
      run: cmake --build ${{ matrix.build-type }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.build-type }}
        retention-days: 1
        path: |
          ${{ matrix.build-type }}
          !${{ matrix.build-type }}/deps
          !${{ matrix.build-type }}/CMakeFiles
          !${{ matrix.build-type }}/catch2-prefix
          !${{ matrix.build-type }}/googlebenchmark-prefix
    needs: [format-check]

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Release, Debug, Sanitize]
    container:
      image: docker.pkg.github.com/little-big-h/buildenvironment/wolframbased:latest
      credentials:
         username: little-big-h
         password: 71589973e27e38bae496e2f4b49be18d2c4fc9f0
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.build-type }}
    - name: test
      run: |
        echo "${{ secrets.MATHEMATICA_LICENSE }}" > mathpass
        chmod +x ./Tests && ./Tests
    needs: [build]

